//  LOGIN
export const AUTH_LOGIN = 'AUTH_LOGIN';
// SIGNUP
export const AUTH_SIGNUP_REQUEST = 'AUTH_SIGNUP_REQUEST';
export const AUTH_SIGNUP_SUCCESS = 'AUTH_SIGNUP_SUCCESS';
export const AUTH_SIGNUP_FAIL = 'AUTH_SIGNUP_FAIL';
// SIGNOUT
export const AUTH_SIGNOUT = 'AUTH_SIGNOUT';
